name: Add native binaries to release

on:
  release:
    types: [created]

jobs:
  prebuild:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build
        run: |
          npm install --ignore-scripts

      - name: Prebuild
        run: |
          npm run prebuild

      - name: Upload
        run: |
          npx prebuild --upload ${{ secrets.UPLOAD_TOKEN }}
        env:
          MAKEFLAGS: -j4

  prebuild-alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ arm64, amd64 ]
        distro: [ "node:18.14.1-alpine3.17" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch }}

      - name: Run in Docker
        run: |
          docker run                                              \
            --rm                                                  \
            -v $(pwd):/${{ github.workspace }}                    \
            -w ${{ github.workspace }}                            \
            --platform linux/${{ matrix.arch }}                   \
            --env MAKEFLAGS=-j4                                   \
            ${{ matrix.distro }}                                  \
              apk add build-base make python3 &&                  \
              npm install --ignore-scripts &&                     \
              npm run prebuild &&                                 \
              npx prebuild --libc musl --arch ${{ matrix.arch }} --upload ${{ secrets.UPLOAD_TOKEN }} 
