on:
  workflow_dispatch:

name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: get python version
        id: python
        run: |
          echo "version=$(python3 -V | awk '{split($2,a,"."); print "{\"major\":"a[1]",\"minor\":"a[2]",\"patch\":"a[3]"}"}')" >> $GITHUB_OUTPUT

      - name: debug python version
        run: |
          echo "JSON: ${{ steps.python.outputs.version }}"
          echo "Major: ${{ fromJSON(steps.python.outputs.version).major }}"
          echo "Minor: ${{ fromJSON(steps.python.outputs.version).minor }}"
          echo "Patch: ${{ fromJSON(steps.python.outputs.version).patch }}"

      - name: fix python3.12 missing distutils
        run: python3 -m pip install packaging setuptools
        if: ${{ fromJSON(steps.python.outputs.version).major >= 3 && fromJSON(steps.python.outputs.version).minor >= 12 }}

